# Generated by Django 3.0.2 on 2020-02-09 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_auto_20200209_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='amount',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='confirmation_code',
            field=models.CharField(default=12, max_length=100),
            preserve_default=False,
        ),
    ]
