# Generated by Django 3.0 on 2020-01-09 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='Organisation Name',
            field=models.CharField(max_length=255),
        ),
    ]
