# Generated by Django 3.0 on 2020-01-09 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20200109_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='Profile Picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.Organisation'),
        ),
    ]
