# Generated by Django 3.0 on 2020-01-09 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20200109_1839'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organisation',
            old_name='Organisation Name',
            new_name='Organisation_Name',
        ),
    ]
