# Generated by Django 3.0.2 on 2020-01-21 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0001_initial'),
        ('authentication', '0005_myuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organisations.Organisation'),
        ),
        migrations.DeleteModel(
            name='Organisation',
        ),
    ]
