# Generated by Django 3.0.2 on 2020-03-02 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_auto_20200121_2026'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='Organisation Admin',
            field=models.BooleanField(default=False),
        ),
    ]
