# Generated by Django 3.0 on 2020-01-18 12:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('OPN', 'Open'), ('PEN', 'Pending'), ('ONH', 'On Hold'), ('CLS', 'Closed')], default='NEW', max_length=3)),
                ('Raised On', models.DateTimeField(auto_now=True)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MED', 'Medium'), ('HGH', 'High')], max_length=3)),
                ('closed_on', models.DateTimeField(blank=True, null=True)),
                ('closure_message', models.CharField(blank=True, max_length=150, null=True)),
                ('associated_users', models.ManyToManyField(blank=True, related_name='_ticket_associated_users_+', to=settings.AUTH_USER_MODEL)),
                ('raised_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
