# Generated by Django 3.0 on 2020-01-18 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_myuser_role'),
        ('ticket', '0002_ticket_assigned_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='assigned_to',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'AGN'}, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.MyUser'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='associated_users',
            field=models.ManyToManyField(blank=True, related_name='_ticket_associated_users_+', to='authentication.MyUser'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='raised_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='authentication.MyUser'),
        ),
    ]
