# Generated by Django 3.0.2 on 2020-02-16 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_auto_20200121_2026'),
        ('ticket', '0007_auto_20200213_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='associated_users',
            field=models.ManyToManyField(blank=True, null=True, related_name='_ticket_associated_users_+', to='authentication.MyUser'),
        ),
    ]
