# Generated by Django 3.0.2 on 2020-03-15 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0008_auto_20200216_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='raised_on',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='updated_on',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
